# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# findwatershed.py
# Created on: 2014-10-17 11:51:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
flow_dir = "C:\\Users\\ac418\\Documents\\India_GIS\\flow_dir"
Export_Hydro_Plant = "Export_Hydro_Plant"
accumulation = "C:\\Users\\ac418\\Documents\\India_GIS\\accumulation"
export_data = "C:\\Users\\ac418\\Documents\\India_GIS\\export_data"
Export_UDel_Rain = "Export_UDel_Rain"
SnapPou_shp1 = "C:\\Users\\ac418\\Documents\\ArcGIS\\Default1.gdb\\SnapPou_shp1"
Watersh_flow1 = "C:\\Users\\ac418\\Documents\\ArcGIS\\Default1.gdb\\Watersh_flow2"
RasterT_Watersh1 = "C:\\Users\\ac418\\Documents\\ArcGIS\\Default1.gdb\\RasterT_Watersh1"
I_Export_Hydro_Plant_FID = "I_Export_Hydro_Plant_FID"
Export_UDel_Rain__3_ = "Export_UDel_Rain"
Export_UDel_Rain__4_ = "Export_UDel_Rain"
rain_map_Value__shp = "C:\\Users\\ac418\\Documents\\India_GIS\\export_data\\rain_map%Value%.shp"
rain_map_hydro__Value__csv = "C:\\Users\\ac418\\Documents\\India_GIS\\export_data\\rain_map_hydro_%Value%.csv"

# Process: Iterate Row Selection
arcpy.IterateRowSelection_mb(Export_Hydro_Plant, "FID #", "true")

# Process: Snap Pour Point
arcpy.gp.SnapPourPoint_sa(I_Export_Hydro_Plant_FID, accumulation, SnapPou_shp1, "0.002", "index")

# Process: Watershed
arcpy.gp.Watershed_sa(flow_dir, SnapPou_shp1, Watersh_flow1, "Value")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(Watersh_flow1, RasterT_Watersh1, "SIMPLIFY", "Value")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(Export_UDel_Rain, "WITHIN_A_DISTANCE", RasterT_Watersh1, "30 Kilometers", "NEW_SELECTION")

# Process: Calculate Field
arcpy.CalculateField_management(Export_UDel_Rain__4_, "Hydro_Plan", Value, "VB", "")

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(Export_UDel_Rain__3_, export_data, "rain_map%Value%.shp", "", "", "")

# Process: Export Feature Attribute to ASCII
arcpy.ExportXYv_stats(rain_map_Value__shp, "FID;lat;lon;Hydro_Plan", "COMMA", rain_map_hydro__Value__csv, "ADD_FIELD_NAMES")

# Process: Feature Class to Feature Class (2)
arcpy.FeatureClassToFeatureClass_conversion(RasterT_Watersh1, export_data, "watershed_hydro%Value%.shp", "", "Shape_Leng \"Shape_Leng\" false false true 0 Double 0 0 ,First,#,C:\\Users\\ac418\\Documents\\ArcGIS\\Default.gdb\\RasterT_Watersh1,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false false true 0 Double 0 0 ,First,#,C:\\Users\\ac418\\Documents\\ArcGIS\\Default.gdb\\RasterT_Watersh1,Shape_Area,-1,-1;ID \"ID\" true true false 0 Long 0 0 ,First,#,C:\\Users\\ac418\\Documents\\ArcGIS\\Default.gdb\\RasterT_Watersh1,ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 0 Long 0 0 ,First,#,C:\\Users\\ac418\\Documents\\ArcGIS\\Default.gdb\\RasterT_Watersh1,GRIDCODE,-1,-1", "")

