BT = chr(96)  # backtick
SQ = chr(39)  # single quote

def bt(varname):
    return BT + varname + SQ

path = "C:/Users/Usuario/Documents/GitHub/twfe_survey/replications/2010-2012/Gentzkow et al. (2011)/run_twowayfe.do"
L = []
a = L.append

a('cap log close _all')
a('log using "C:/Users/Usuario/Documents/GitHub/twfe_survey/replications/2010-2012/Gentzkow et al. (2011)/run_twowayfe.log", text replace')
a('set more off')
a('set matsize 5000')
a('')
a('adopath + "C:/Users/Usuario/Documents/GitHub/twfe_survey/data/2010-2012/Gentzkow et al. (2011)/20091316_data/external"')
a('loadglob using "C:/Users/Usuario/Documents/GitHub/twfe_survey/data/2010-2012/Gentzkow et al. (2011)/20091316_data/code/input_param.txt"')
a('global maxwindow = 1')
a('')
a('use "C:/Users/Usuario/Documents/GitHub/twfe_survey/data/2010-2012/Gentzkow et al. (2011)/20091316_data/temp/voting_cnty_clean.dta", clear')
a('')
a('di "============================================="')
a('di "TABLE 2 REPLICATION"')
a('di "============================================="')
a('')
a('define_event x, changein(numdailies) maxchange($maxchange) window(1)')
a('')
a('areg D.prestout x_0 if mainsample, absorb(styr) cluster(cnty90)')
a('local b_col2 = _b[x_0]')
a('local se_col2 = _se[x_0]')
a('local n_col2 = e(N)')
a('local nc_col2 = e(N_clust)')
a('')
a('areg D.prestout x_0 $demolist $misdemolist if mainsample, absorb(styr) cluster(cnty90)')
a('local b_col3 = _b[x_0]')
a('local se_col3 = _se[x_0]')
a('local n_col3 = e(N)')
a('local nc_col3 = e(N_clust)')
a('')
a('areg D.congtout x_0 $demolist $misdemolist if mainsample & abs(D.congtout)<1, absorb(styr) cluster(cnty90)')
a('local b_col4 = _b[x_0]')
a('local se_col4 = _se[x_0]')
a('local n_col4 = e(N)')
a('local nc_col4 = e(N_clust)')
a('')
a('di "============================================="')
a('di "TWOWAYFEWEIGHTS"')
a('di "============================================="')
a('')
a('keep if mainsample == 1')
a('di "Restricted to mainsample: N = " _N')
a('')
a('* T=year version')
a('cap noisily twowayfeweights prestout cnty90 year numdailies, type(feTR)')
a('local tw_rc1 = _rc')
a(f'if {bt("tw_rc1")} == 0 | {bt("tw_rc1")} == 402 ' + '{')
a('    local tw_beta1  = e(beta)')
a('    mat _M1 = e(M)')
a('    local tw_npos1  = _M1[1,1]')
a('    local tw_nneg1  = _M1[2,1]')
a(f'    local tw_ntot1  = {bt("tw_npos1")} + {bt("tw_nneg1")}')
a(f'    local tw_pneg1 : di %5.1f (100 * {bt("tw_nneg1")} / {bt("tw_ntot1")})')
a(f'    di "T=year: beta=" {bt("tw_beta1")} ", npos=" {bt("tw_npos1")} ", nneg=" {bt("tw_nneg1")} ", %neg=" {bt("tw_pneg1")}')
a('}')
a('else {')
a(f'    di "twowayfeweights (T=year) FAILED rc=" {bt("tw_rc1")}')
a('    local tw_beta1  = .')
a('    local tw_npos1  = .')
a('    local tw_nneg1  = .')
a('    local tw_pneg1  = "N/A"')
a('}')
a('')
a('* T=styr version (matches paper spec)')
a('cap noisily twowayfeweights prestout cnty90 styr numdailies, type(feTR)')
a('local tw_rc2 = _rc')
a(f'if {bt("tw_rc2")} == 0 | {bt("tw_rc2")} == 402 ' + '{')
a('    local tw_beta2  = e(beta)')
a('    mat _M2 = e(M)')
a('    local tw_npos2  = _M2[1,1]')
a('    local tw_nneg2  = _M2[2,1]')
a(f'    local tw_ntot2  = {bt("tw_npos2")} + {bt("tw_nneg2")}')
a(f'    local tw_pneg2 : di %5.1f (100 * {bt("tw_nneg2")} / {bt("tw_ntot2")})')
a(f'    di "T=styr: beta=" {bt("tw_beta2")} ", npos=" {bt("tw_npos2")} ", nneg=" {bt("tw_nneg2")} ", %neg=" {bt("tw_pneg2")}')
a('}')
a('else {')
a(f'    di "twowayfeweights (T=styr) FAILED rc=" {bt("tw_rc2")}')
a('    local tw_beta2  = .')
a('    local tw_npos2  = .')
a('    local tw_nneg2  = .')
a('    local tw_pneg2  = "N/A"')
a('}')
a('')
a('di "============================================="')
a('di "SUMMARY"')
a('di "============================================="')
a(f'di "Col 2: beta=" %7.4f {bt("b_col2")} " se=" %7.4f {bt("se_col2")} " N=" {bt("n_col2")}')
a(f'di "Col 3: beta=" %7.4f {bt("b_col3")} " se=" %7.4f {bt("se_col3")} " N=" {bt("n_col3")}')
a(f'di "Col 4: beta=" %7.4f {bt("b_col4")} " se=" %7.4f {bt("se_col4")} " N=" {bt("n_col4")}')
a(f'di "twowayfe T=year: rc=" {bt("tw_rc1")}')
a(f'di "twowayfe T=styr: rc=" {bt("tw_rc2")}')
a('')
a('log close')

with open(path, 'w') as f:
    f.write('\n'.join(L))
print(f'Gentzkow do file written: {len(L)} lines')
