path = "C:/Users/Usuario/Documents/GitHub/twfe_survey/replications/2010-2012/Dinkelman (2011)/run_twowayfe.do"
lines = []
a = lines.append

a('cap log close _all')
a('log using "C:/Users/Usuario/Documents/GitHub/twfe_survey/replications/2010-2012/Dinkelman (2011)/run_twowayfe.log", text replace')
a('set more off')
a('')
a('use "C:/Users/Usuario/Documents/GitHub/twfe_survey/data/2010-2012/Dinkelman (2011)/20080791_dataset/data/matched_censusdata.dta", clear')
a('keep if largearea == 1')
a('di "Sample N = " _N')
a('')
a('global x1 "kms_to_subs0 baseline_hhdens0 base_hhpovrate0 prop_head_f_a0 sexratio0 prop_indianwhite0 kms_to_road0 kms_to_town0 prop_matric_m0 prop_matric_f0"')
a('')
a('di "============================================="')
a('di "TABLE 4 REPLICATION"')
a('di "============================================="')
a('')
a('di _n "--- Col 1: OLS, no controls ---"')
a('reg d_prop_emp_f T, robust cluster(placecode0)')
a('local b_ols1 = _b[T]')
a('local se_ols1 = _se[T]')
a('local n_ols1 = e(N)')
a('')
a('di _n "--- Col 3: OLS, controls + district FE ---"')
a('xi: reg d_prop_emp_f T $x1 i.dccode0, robust cluster(placecode0)')
a('local b_ols3 = _b[T]')
a('local se_ols3 = _se[T]')
a('local n_ols3 = e(N)')
a('')
a('di _n "--- Col 5: IV, no controls ---"')
a('ivregress 2sls d_prop_emp_f (T = mean_grad_new), robust cluster(placecode0) first')
a('local b_iv5 = _b[T]')
a('local se_iv5 = _se[T]')
a('local n_iv5 = e(N)')
a('')
a('di _n "--- Col 7: IV, controls + district FE ---"')
a('xi: ivregress 2sls d_prop_emp_f (T = mean_grad_new) $x1 i.dccode0, robust cluster(placecode0) first')
a('local b_iv7 = _b[T]')
a('local se_iv7 = _se[T]')
a('local n_iv7 = e(N)')
a('')
a('di _n "--- Male: OLS+FE ---"')
a('xi: reg d_prop_emp_m T $x1 i.dccode0, robust cluster(placecode0)')
a('local b_ols3m = _b[T]')
a('local se_ols3m = _se[T]')
a('')
a('di _n "--- Male: IV+FE ---"')
a('xi: ivregress 2sls d_prop_emp_m (T = mean_grad_new) $x1 i.dccode0, robust cluster(placecode0)')
a('local b_iv7m = _b[T]')
a('local se_iv7m = _se[T]')
a('')
a('* --- Reshape to 2-period panel ---')
a('di _n "============================================="')
a('di "RESHAPING TO 2-PERIOD PANEL"')
a('di "============================================="')
a('')
a('use "C:/Users/Usuario/Documents/GitHub/twfe_survey/data/2010-2012/Dinkelman (2011)/20080791_dataset/data/matched_censusdata.dta", clear')
a('keep if largearea == 1')
a('keep placecode0 dccode0 T mean_grad_new prop_emp_f0 prop_emp_f1 prop_emp_m0 prop_emp_m1 $x1')
a('')
a('gen comm_id = _n')
a('local N_comm = _N')
a('')
a('expand 2')
a('sort comm_id')
a('by comm_id: gen year = cond(_n == 1, 1996, 2001)')
a('')
a('gen prop_emp_f = cond(year == 1996, prop_emp_f0, prop_emp_f1)')
a('gen prop_emp_m = cond(year == 1996, prop_emp_m0, prop_emp_m1)')
a('gen D = cond(year == 2001, T, 0)')
a('')
a('xtset comm_id year, delta(5)')
a('di "Panel: " _N " obs = " `N_comm\' " communities x 2 periods"')
a('')
a('* --- Levels TWFE regression ---')
a('reg prop_emp_f D i.comm_id i.year, cluster(placecode0)')
a('di "TWFE beta = " _b[D]')
a('di "TWFE se   = " _se[D]')
a('')
a('* --- twowayfeweights ---')
a('di _n "============================================="')
a('di "TWOWAYFEWEIGHTS - Female Employment"')
a('di "============================================="')
a('')
a('cap noisily twowayfeweights prop_emp_f comm_id year D, type(feTR)')
a('local tw_rc1 = _rc')
a('if `tw_rc1\' == 0 | `tw_rc1\' == 402 {')
a('    local tw_beta1  = e(beta)')
a('    mat _M1 = e(M)')
a('    local tw_npos1  = _M1[1,1]')
a('    local tw_nneg1  = _M1[2,1]')
a('    local tw_ntot1  = `tw_npos1\' + `tw_nneg1\'')
a('    local tw_pneg1 : di %5.1f (100 * `tw_nneg1\' / `tw_ntot1\')')
a('    di _n "Beta TWFE     = " `tw_beta1\'')
a('    di "# pos weights = " `tw_npos1\'')
a('    di "# neg weights = " `tw_nneg1\'')
a('    di "% neg weights = " `tw_pneg1\' "%"')
a('}')
a('else {')
a('    di "twowayfeweights FAILED with rc = " `tw_rc1\'')
a('    local tw_beta1  = .')
a('    local tw_npos1  = .')
a('    local tw_nneg1  = .')
a('    local tw_pneg1  = "N/A"')
a('}')
a('')
a('di _n "============================================="')
a('di "TWOWAYFEWEIGHTS - Male Employment"')
a('di "============================================="')
a('')
a('cap noisily twowayfeweights prop_emp_m comm_id year D, type(feTR)')
a('local tw_rc2 = _rc')
a('if `tw_rc2\' == 0 | `tw_rc2\' == 402 {')
a('    local tw_beta2  = e(beta)')
a('    mat _M2 = e(M)')
a('    local tw_npos2  = _M2[1,1]')
a('    local tw_nneg2  = _M2[2,1]')
a('    local tw_ntot2  = `tw_npos2\' + `tw_nneg2\'')
a('    local tw_pneg2 : di %5.1f (100 * `tw_nneg2\' / `tw_ntot2\')')
a('    di _n "Beta TWFE     = " `tw_beta2\'')
a('    di "# pos weights = " `tw_npos2\'')
a('    di "# neg weights = " `tw_nneg2\'')
a('    di "% neg weights = " `tw_pneg2\' "%"')
a('}')
a('else {')
a('    di "twowayfeweights FAILED with rc = " `tw_rc2\'')
a('    local tw_beta2  = .')
a('    local tw_npos2  = .')
a('    local tw_nneg2  = .')
a('    local tw_pneg2  = "N/A"')
a('}')
a('')
a('* --- Summary ---')
a('di _n "============================================="')
a('di "SUMMARY"')
a('di "============================================="')
a('di "Table 4 replication:"')
a('di "  Female OLS (no ctrl): beta = " %7.4f `b_ols1\' " (" %7.4f `se_ols1\' ")"')
a('di "  Female OLS+FE:        beta = " %7.4f `b_ols3\' " (" %7.4f `se_ols3\' ")"')
a('di "  Female IV (no ctrl):  beta = " %7.4f `b_iv5\' " (" %7.4f `se_iv5\' ")"')
a('di "  Female IV+FE:         beta = " %7.4f `b_iv7\' " (" %7.4f `se_iv7\' ")"')
a('di ""')
a('di "twowayfeweights (female): rc = " `tw_rc1\'')
a('if `tw_rc1\' == 0 | `tw_rc1\' == 402 {')
a('    di "  beta = " `tw_beta1\' ", # pos = " `tw_npos1\' ", # neg = " `tw_nneg1\' ", % neg = " `tw_pneg1\' "%"')
a('}')
a('di "twowayfeweights (male): rc = " `tw_rc2\'')
a('if `tw_rc2\' == 0 | `tw_rc2\' == 402 {')
a('    di "  beta = " `tw_beta2\' ", # pos = " `tw_npos2\' ", # neg = " `tw_nneg2\' ", % neg = " `tw_pneg2\' "%"')
a('}')
a('')
a('log close')

# Fix backtick escaping - Python used \' but Stata needs actual backtick
content = '\n'.join(lines)
content = content.replace("\'" , "`")  # restore Stata backticks

with open(path, 'w') as f:
    f.write(content)
print("Dinkelman run_twowayfe.do written successfully")
